# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn lint
    - run: yarn test:ci
    - run: yarn testing
      env:
        api_base: ${{ secrets.API_BASE }}
        client_id: ${{ secrets.CLIENT_ID }}
        openid_audience: ${{ secrets.OPENID_AUDIENCE }}
        openid_authority: ${{ secrets.OPENID_AUTHORITY }}
        local_storage_user_expiry_time: ${{ secrets.LOCAL_STORAGE_USER_EXPIRY_TIME }}
        nocache: ${{ secrets.NOCACHE }}
        raven_id: ${{ secrets.RAVEN_ID }}
        city_theme: ${{ secrets.CITY_THEME }}
        show_cookie_bar: ${{ secrets.SHOW_COOKIE_BAR }}
    
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
 
